### ISSUE TITLE
Make the mod panel access link more visible.

### ISSUE THREAD

**Issue by pirwen** [SyndroneOnline/SyndroneOnline.com#17]
The only way to access it as of now is a small text link. Maybe add a button someone in the menu for mods only.

**Comment by pirwen** [comment]
Can we add another category for necessary 'enhancements'? Haha, I think this one would be more of a MUST have.

**Comment by pirwen** [comment]
![image](https://cloud.githubusercontent.com/assets/22144244/18496342/ff4ea3c8-79d9-11e6-9458-ce476ac33504.png)

Sorry, the more I see it, the less sense it makes

**Comment by emiliobool** [comment]
so we are probably going to make a lot more new changes but for the time being

![unspecified](https://cloud.githubusercontent.com/assets/2165828/19032931/4df77f72-8911-11e6-9d6f-bd1f44b24a3d.png)
