### ISSUE TITLE
Cookie issue

### ISSUE THREAD

**Issue by emiliobool** [SyndroneOnline/SyndroneOnline.com#4]
Sometimes on mobile bugs and wont let log in, in and out

**Comment by pirwen** [comment]
When it happens you do get a 'You have successfully logged in' greeting, and it shows notifications that do not necessarily exist. Then it logs you out and redirects to the landing page. I have to use an incognito window for it to work.

**Comment by emiliobool** [comment]
ok I found this issue, it is related with the android chrome browser which uses a proxy to compress all images and data, which in turn disables all cookies, the first landing page after login doesn't require cookies and that's why it appears to be logged in, but it never persists

I will look into a solution for this

**Comment by emiliobool** [comment]
ok I remember now, google states they don't compress the data when using https, but using https aside from buying/requesting/setting up a certificate  means being forced to load all assets on the site as https, thing that conflicts with using a cdn which in turn would need to have its own certificate installed, I believe using custom certificates on cdn is easier now, and cost a lot less too, but still something to consider if we want to get into

one solution could also be showing a message when detecting the google proxy and ask them to disable it, im inclined for this solution but also up to reviewing the pros and cons of running the entire site over https

**Comment by emiliobool** [comment]
as per #26 we dont want to do https right now, so the solution would be #27
